version: "3"

services:
  colobot:
    image: colobot
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/snd:/dev/snd"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/run/user/1000/pulse:/run/pulse:ro"
      - "./.colobot:/home/game/.local/share/colobot"
    networks:
      - main

networks:
  main:
